# Site settings
title: Garrick S. Bodine
email: garrick.bodine@gmail.com
url: https://gsbodine.github.io
description: "GSB: Integrator of Code, Systems, and People"

# Contact form: comment the line below if you want to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: A0CAD8 #18bc9c #80B3FF
  secondary: 415162 #2c3e50 #FD6E8A
  secondary-dark: 002500 #233140 #A2122F

# Footer settings
footer:
  copyright: Garrick S. Bodine
  location: Seattle, WA
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/garricks
  - title: bitbucket
    url: http://bitbucket.org/gsbodine
  - title: github
    url: http://github.com/gsbodine

# Postal address (add as many lines as necessary)
address:
  - line: Bellevue, WA 98004

# Credits content
credits: 'Theme based on <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty
